server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  rabbitmq: # 远程连接到Linux上的RabbitMQ，需要配置rabbitmq连接
    host: 192.168.184.134
    port: 5672
    username: root
    password: abc123
  cloud:
    stream:
      bindings:   # 服务的整合处理
        msgSource-out-0:  # 通道的名字   注意:bindings 集合中的key由 通道名(bean的名字)-out/in-数字组成
          destination: msg-topic  # 目的地，即Exchange
          content-type: application/json   # 设置消息类型，本次为json   文本：text/plain

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #入住地址 集群版
  instance:
    lease-renewal-interval-in-seconds: 2  #Eureka客户端向服务店端发送心跳的时间间隔，单位为秒 （默认30s
    lease-expiration-duration-in-seconds: 5  #Eureka服务端在收到最后一次心跳后等待时间上限，超时将剔除服务，单位为秒  (默认30s
