server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:    # 路由是多个，可以给某个controller中的多个接口做路由
        - id: payment_route1       # 路由的ID，没有固定规则，但要求唯一 （建议配合服务名
#          uri: http://localhost:8001       # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     # 匹配后提供服务的微服务名称
          predicates:
            - Path=/payment/get/**    # 断言，路径相匹配的进行路由
            - After=2022-10-31T15:08:17.361344900+08:00[Asia/Shanghai]
#            - Cookie=username,uyyu    # 要求携带username=uyyu键值对的cookie
#            - Header=X-Request-Id, \d+   # 要求请求头有X-Request-Id属性并且值为整数的正则表达式

        - id: payment_route2       # 路由的ID，没有固定规则，但要求唯一 （建议配合服务名
#          uri: http://localhost:8001       # 匹配后提供服务的路由地址
          uri: lb://cloud-payment-service     # 匹配后提供服务的微服务名称
          predicates:
            - Path=/payment/create    # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  #入住地址 集群版

