server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com  #eureka服务端的实例名称  不要和集群中的重名！
  client:
    register-with-eureka: false  #是否向注册中心注册自己（注册中心本身不用注册）
    fetch-registry: false  #是否从Eureka Server获取注册的服务信息
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/ #集群版
#      defaultZone: http://eureka7001.com:7001/eureka/ #单机版
      #设置EurekaServer的访问地址，可以在此查询与Eureka Server交互的地址查询服务和注册服务
      #集群中“相互注册，互相守望”。7001注册7002,7002注册7001
      #单机版，自己注册自己即可
#  server:
#    enable-self-preservation: false #自我保护模式，默认是true 开启
#    eviction-interval-timer-in-ms: 2000  # 检测心跳的时间  默认是90s （90s内未收到心跳会移除该服务