server:
  port: 80

spring:
  application:
    name: cloud-consumer-order
  cloud:
    # 注册到zookeeper
    zookeeper:
      connect-string: 192.168.184.134:2181,192.168.184.135:2181,192.168.184.136:2181